print("##############################")
print("#                            #")
print("#   Muhammad Rakha'Athallah  #")
print("#        2410817310002       #")
print("#                            #")
print("##############################")